@startuml
[*] --> BACKLOG
BACKLOG --> IN_PROGRESS:START_FEATURE
IN_PROGRESS --> TESTING:FINISH_FEATURE
IN_PROGRESS --> IN_PROGRESS:deploy
TESTING --> DONE: QA_TEAM_APPROVE
TESTING --> IN_PROGRESS: QA_TEAM_REJECT
BACKLOG --> TESTING:ROCK_STAR
BACKLOG --> BACKLOG:deploy
@enduml