@startuml
[*] --> BACKLOG
BACKLOG --> IN_PROGRESS:START_FEATURE
IN_PROGRESS --> TESTING:FINISH_FEATURE
TESTING --> DONE: QA_TEAM_APPROVE
TESTING --> IN_PROGRESS: QA_TEAM_REJECT
BACKLOG --> TESTING:ROCK_STAR
@enduml